spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.csuupodcoobr.ap-northeast-2.rds.amazonaws.com:13306/music-forecast?createDatabaseIfNotExist=true
    username: admin
    password: musicforecast
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 121646054560-tgn23qhkfbno1lhgj0v4odq7p9gjlqkc.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
          kakao:
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000
            client-id: 4c5d1970a764dd126fa0800e2b151812
            client-secret: 3cMajN46UJ0ZVCVityDGQMPzttKqjVey
            scope:
              - account_email
            client-authentication-method: GET
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420
weather:
  api:
    key: ${WEATHER_API_KEY}
spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret: ${SPOTIFY_CLIENT_SECRET}